- id: remove-unreferenced-image
  name: check if image is not referenced by any file
  entry: pre_commit_hooks/main.sh remove-unreferenced-image
  language: script
  types: [image]
- id: use-webp-image
  name: check if image is in webp format
  entry: pre_commit_hooks/main.sh use-webp-image
  language: script
  require_serial: true
  types: [image]
  exclude_types: [svg]
- id: fix-en-dash-list
  name: fix en dash list which is not recognized as real list
  entry: pre_commit_hooks/main.sh fix-en-dash-list
  language: script
  types: [markdown]
- id: no-full-uri-for-internal-pages
  name: fix full URI link for internal pages
  entry: pre_commit_hooks/main.sh no-full-uri-for-internal-pages
  language: script
  types: [markdown]
